CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" char(30) UNIQUE NOT NULL,
  "user_id" char(150) UNIQUE NOT NULL,
  "joied_at" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "projects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "project_name" char(50) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "access" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "project_id" integer NOT NULL,
  "permission" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "permissions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" char(20) DEFAULT null
);

CREATE TABLE IF NOT EXISTS "gantt_charts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "project_id" integer NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "title" char(50) NOT NULL,
  "description" char(255) NOT NULL DEFAULT '',
  "completed" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "group_contracts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "project_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "group_contracts_content" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "parent" integer DEFAULT null,
  "group_contract_id" integer NOT NULL,
  "rule_title" char(50) NOT NULL DEFAULT '',
  "rule_description" text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "project_id" integer NOT NULL,
  "sender_id" integer NOT NULL,
  "message" text NOT NULL,
  "time_sent" timestamp DEFAULT (now())
);

ALTER TABLE IF EXISTS "projects" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE IF EXISTS "access" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE IF EXISTS "access" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE IF EXISTS "access" ADD FOREIGN KEY ("permission") REFERENCES "permissions" ("id");

ALTER TABLE IF EXISTS "gantt_charts" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE IF EXISTS "group_contracts" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE IF EXISTS "group_contracts_content" ADD FOREIGN KEY ("group_contract_id") REFERENCES "group_contracts" ("id");

ALTER TABLE IF EXISTS "messages" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id");

ALTER TABLE IF EXISTS "messages" ADD FOREIGN KEY ("sender_id") REFERENCES "users" ("id");